language: java
sudo: false

before_install:
  - echo 'MAVEN_OPTS="-Dorg.slf4j.simpleLogger.defaultLogLevel=warn"' >~/.mavenrc

matrix:
  fast_finish: true
  include:
    # checkstyle
    - jdk: oraclejdk7
      env:
        - DESC="checkstyle"
        - CMD="mvn clean checkstyle:check"
    # unit tests (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="oraclejdk8 unit tests"
        - CMD="mvn clean test -Dcheckstyle.skip=true"
    # unit tests (oraclejdk7)
    - jdk: oraclejdk7
      env:
        - DESC="oraclejdk7 unit tests"
        - CMD="mvn clean test -Dcheckstyle.skip=true"
    # unit tests (openjdk7)
    - jdk: openjdk7
      env:
        - DESC="openjdk7 unit tests"
        - CMD="mvn clean test -Dcheckstyle.skip=true"

script: echo ${CMD}; ${CMD}
